version: 2

machine:
  services:
    - docker

base_image: &base_image
  image: circleci/node:10-browsers
  environment:
          CHROME_BIN: "/usr/bin/google-chrome"

job_common: &job_common
  docker:
    - <<: *base_image

save: &save
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - .
      # save the git commit and ssh config
      - ".git"
      - "~/.ssh"
      - "node_modules"

restore: &restore
  restore_cache:
     key: dependency-cache-{{ checksum "package.json" }}

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t brunnerl6/lxdhub-web .

  test:
    <<: *job_common
    steps:
      - checkout
      - <<: *restore
      - run:
          name: Setup Dependencies
          command: yarn install
      - <<: *save
      - run: yarn run test:ci

  deploy_docker:
    machine: true
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test


