---
- name: Conditionally decide to load in variables file when lxdhub['snap'] is 0, otherwise do not.
  include_vars:
    file: "{{ playbook_dir }}/vars/lxd_snap_socket.yml"
  when: hostvars['{{ container_name }}']['snap'] == "0"

- name: Conditionally decide to load in variables file when lxdhub['snap'] is not 0, otherwise do not.
  include_vars:
    file: "{{ playbook_dir }}/vars/lxd_default_socket.yml"
  when: hostvars['{{ container_name }}']['snap'] != "0"

- debug:
    msg: "container url: {{ lxd_url }}"

- name: Create and start container
  lxd_container:
    name: "{{ container_name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ubuntu/bionic/amd64
    profiles: ["default"]
    config: {"security.nesting": "true"}
    url: "{{ lxd_url }}"
    wait_for_ipv4_addresses: true
    timeout: 600

- name: install python in container
  command: 'lxc exec {{ container_name }} -- sh -c "apt update && apt install -y python"'
