version: 2

machine:
  services:
    - docker

jobs:
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/lxdhub
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ./bin/run-tests.sh
      - run: npm run lint

  build_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: docker build -f Dockerfile.api .
      - run: docker build -f Dockerfile.dbsync .

  deploy_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

workflows:
  version: 2

  build-test-and-deploy:
    jobs:
      - test
      - build_docker
      - deploy_docker:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - build_docker
            - test

