version: 2

machine:
  services:
    - docker

jobs:
  test:
    machine: true
    working_directory: ~/lxdhub
    steps:
      - checkout
      - run: docker build -f Dockerfile.api -t brunnel6/lxdhub-api .
      - run: docker run -it brunnel6/lxdhub-api test
      - run: docker run -it brunnel6/lxdhub-api lint

  build_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: docker build -f Dockerfile.api .
      - run: docker build -f Dockerfile.dbsync .

  deploy_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

workflows:
  version: 2

  build-test-and-deploy:
    jobs:
      - test
      - build_docker
      - deploy_docker:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - build_docker
            - test

