version: 2

base_image: &base_image
  image: circleci/node:8.9.4

job_common: &job_common
  docker:
    - <<: *base_image

save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      # save the git commit and ssh config
      - ".git"
      - "~/.ssh"

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

machine:
  services:
    - docker

jobs:
  lockfile_update:
    <<: *job_common
    steps:
      - checkout
      - run: |
          sudo yarn global add greenkeeper-lockfile@2
          greenkeeper-lockfile-update
          echo lockfile_update installed greenkeeper-lockfile and ran greenkeeper-lockfile-update
      - <<: *save

  test:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t brunnel6/lxdhub .
          docker run -it brunnel6/lxdhub test
          docker run -it brunnel6/lxdhub lint

  lockfile_upload:
    <<: *job_common
    steps:
      - <<: *restore
      - run: |
          sudo yarn global add greenkeeper-lockfile@2
          greenkeeper-lockfile-upload
          echo lockfile_upload ran greenkeeper-lockfile-upload

  npm_deploy:
    <<: *job_common
    steps:
      - checkout
      - run: |
          sudo yarn global add lerna
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          lerna publish --yes --canary --no-git-tag-version --no-verify-access --dist-tag $([ -z "$CIRCLE_TAG" ] && echo "unstable" || echo "latest")


  build_lxdhub_image:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      # setup dependencies
      - run: |
          sudo apt purge --yes lxd lxd-client
          sudo apt-add-repository ppa:ansible/ansible -y
          sudo apt update
          sudo apt install --yes ansible snap
      # install lxd via snap because ubuntu version is to old (and xenial-backports fails)
      - run: |
          sudo snap install lxd
          cat ansible/roles/lxd_setup/files/lxd.seed | sudo /snap/bin/lxd init --preseed
          echo 'export PATH=/snap/bin:$PATH' >> $BASH_ENV
      # install lxdhub
      - run: |
          lxc launch ubuntu:18.04 lxdhub
          # wait for the container to start up see: https://blog.simos.info/how-to-know-when-a-lxd-container-has-finished-starting-up/
          lxc exec lxdhub -- bash -c 'while [ "$(systemctl is-system-running 2>/dev/null)" != "running" ] && [ "$(systemctl is-system-running 2>/dev/null)" != "degraded" ]; do :; done'
          lxc exec lxdhub -- apt update
          lxc exec lxdhub -- apt install --yes python
          ansible-playbook ansible/install-lxdhub.yml -c lxd -i lxdhub, -e lxdhub_version="$([ ! -z \"$CIRCLE_TAG\" ] && echo 'unstable' || echo 'latest')" -vvv
          lxc stop lxdhub
          lxc publish local:lxdhub --alias lxdhub description="lxdhub $CIRCLE_SHA1 ($(date +%Y%m%d_%H:%M))" --public
          lxc image export local:lxdhub /tmp/lxdhub-img --quiet
      - store_artifacts:
          path: /tmp/lxdhub-img.tar.gz
          destination: lxdhub-img.tar.gz

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lockfile_update
      - test:
          requires:
            - lockfile_update
      - lockfile_upload:
          requires:
            - test
      - build_lxdhub_image:
          requires:
            - npm_deploy
      - npm_deploy:
          requires:
            - test
