---
- name: copy services
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
  with_items:
    - lxdhub.service

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable and start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - lxdhub.service

- name: trigger the dbsync every quarter hour"
  cron:
    name: "run lxdhub dbsync"
    user: "lxdhub"
    minute: "0,15,30,45"
    job: "node /var/lib/lxdhub/lxdhub/packages/dbsync/lib/cli.js start -c /var/lib/lxdhub/lxdhub/lxdhub.yml 2>&1 | /usr/bin/logger -t lxdhub-dbsync"