---
- name: stop lxdhub container
  lxd_container:
    name: "{{ container_name }}"
    state: stopped
    url: unix:/var/snap/lxd/common/lxd/unix.socket

- debug:
    msg: "lxdhub current has is {{ hostvars['lxdhub']['hash'] }}"

- name: generate publish date
  command: date +%Y%m%d_%H:%M
  register: publish_date

- name: publish lxdhub local image
  command: lxc publish "local:{{ container_name }}" --alias "{{ container_name }}" "description=lxdhub {{ hostvars['lxdhub']['hash'] }} ({{ publish_date.stdout }})" --public
