---
- name: Conditionally decide to load in variables file when lxdhub['snap'] is 0, otherwise do not.
  include_vars:
    file: "{{ playbook_dir }}/vars/lxd_snap_socket.yml"
  when: hostvars['{{ container_name }}']['snap'] == "0"

- name: Conditionally decide to load in variables file when lxdhub['snap'] is not 0, otherwise do not.
  include_vars:
    file: "{{ playbook_dir }}/vars/lxd_default_socket.yml"
  when: hostvars['{{ container_name }}']['snap'] != "0"

- debug:
    msg: "container url: {{ lxd_url }}"

- name: stop container
  lxd_container:
    name: "{{ container_name }}"
    state: stopped
    url: "{{ lxd_url }}"

- debug:
    msg: "{{ container_name }} current hash is {{ hostvars['git']['hash'] }}"

- name: generate publish date
  command: date +%Y%m%d_%H:%M
  register: publish_date

- name: publish lxdhub local image
  command: lxc publish "local:{{ container_name }}" --alias "{{ container_name }}" "description=lxdhub {{ hostvars['git']['hash'] }} ({{ publish_date.stdout }})" --public
